/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWateringRouteImport } from './routes/_authenticated/watering'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPlantsRouteImport } from './routes/_authenticated/plants'
import { Route as AuthenticatedPesticideRouteImport } from './routes/_authenticated/pesticide'
import { Route as AuthenticatedHarvestRouteImport } from './routes/_authenticated/harvest'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedFertilizerRouteImport } from './routes/_authenticated/fertilizer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWateringRoute = AuthenticatedWateringRouteImport.update({
  id: '/watering',
  path: '/watering',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantsRoute = AuthenticatedPlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesticideRoute = AuthenticatedPesticideRouteImport.update({
  id: '/pesticide',
  path: '/pesticide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHarvestRoute = AuthenticatedHarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFertilizerRoute = AuthenticatedFertilizerRouteImport.update({
  id: '/fertilizer',
  path: '/fertilizer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fertilizer': typeof AuthenticatedFertilizerRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/harvest': typeof AuthenticatedHarvestRoute
  '/pesticide': typeof AuthenticatedPesticideRoute
  '/plants': typeof AuthenticatedPlantsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watering': typeof AuthenticatedWateringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fertilizer': typeof AuthenticatedFertilizerRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/harvest': typeof AuthenticatedHarvestRoute
  '/pesticide': typeof AuthenticatedPesticideRoute
  '/plants': typeof AuthenticatedPlantsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watering': typeof AuthenticatedWateringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fertilizer': typeof AuthenticatedFertilizerRoute
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/harvest': typeof AuthenticatedHarvestRoute
  '/_authenticated/pesticide': typeof AuthenticatedPesticideRoute
  '/_authenticated/plants': typeof AuthenticatedPlantsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/watering': typeof AuthenticatedWateringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/fertilizer'
    | '/growth'
    | '/harvest'
    | '/pesticide'
    | '/plants'
    | '/reports'
    | '/settings'
    | '/watering'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/fertilizer'
    | '/growth'
    | '/harvest'
    | '/pesticide'
    | '/plants'
    | '/reports'
    | '/settings'
    | '/watering'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/fertilizer'
    | '/_authenticated/growth'
    | '/_authenticated/harvest'
    | '/_authenticated/pesticide'
    | '/_authenticated/plants'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/watering'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watering': {
      id: '/_authenticated/watering'
      path: '/watering'
      fullPath: '/watering'
      preLoaderRoute: typeof AuthenticatedWateringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plants': {
      id: '/_authenticated/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof AuthenticatedPlantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesticide': {
      id: '/_authenticated/pesticide'
      path: '/pesticide'
      fullPath: '/pesticide'
      preLoaderRoute: typeof AuthenticatedPesticideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/harvest': {
      id: '/_authenticated/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof AuthenticatedHarvestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fertilizer': {
      id: '/_authenticated/fertilizer'
      path: '/fertilizer'
      fullPath: '/fertilizer'
      preLoaderRoute: typeof AuthenticatedFertilizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFertilizerRoute: typeof AuthenticatedFertilizerRoute
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedHarvestRoute: typeof AuthenticatedHarvestRoute
  AuthenticatedPesticideRoute: typeof AuthenticatedPesticideRoute
  AuthenticatedPlantsRoute: typeof AuthenticatedPlantsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWateringRoute: typeof AuthenticatedWateringRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFertilizerRoute: AuthenticatedFertilizerRoute,
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedHarvestRoute: AuthenticatedHarvestRoute,
  AuthenticatedPesticideRoute: AuthenticatedPesticideRoute,
  AuthenticatedPlantsRoute: AuthenticatedPlantsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWateringRoute: AuthenticatedWateringRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
